# Generated by Django 5.2.6 on 2025-09-29 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField(choices=[(1, 'Letter to a Character'), (2, 'Paint an old T-shirt'), (3, 'Bottle art'), (4, 'Mud Sculpting')])),
                ('user', models.CharField(max_length=50)),
                ('submission', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
