# Generated by Django 5.2.6 on 2025-10-01 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_submission_image_submission_text_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='image',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='submission',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='task_id',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='text',
        ),
        migrations.AddField(
            model_name='submission',
            name='submission_file',
            field=models.CharField(default='default.png', max_length=255),
        ),
        migrations.AlterField(
            model_name='submission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submission',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='tasks.task'),
            preserve_default=False,
        ),
    ]
